apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: tanzu-app
  namespace: tanzu-app
spec:
  tag: harbor.withtanzu.com/lzetea/tanzu-app
  serviceAccount: tanzu-app-service-account
  builder:
    name: default-builder
    kind: Builder
  source:
    git:
      url: https://github.com/lzetea/tanzu-app
      revision: main
